# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('atype', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_invites', to='accounts.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[(b'S', b'Single Choice'), (b'M', b'Multiple Choice'), (b'T', b'Text Answer'), (b'P', b'Personality quiz')], max_length=1)),
                ('feedback_aspect', models.CharField(blank=True, choices=[(b'CM', b'Communication'), (b'TW', b'Team Work'), (b'LD', b'Leadership'), (b'PO', b'Productivity'), (b'CP', b'Creativity')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_survey_responses', to='accounts.Employee')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='actions.SurveyQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponseChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='actions.SurveyQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actions.Action')),
                ('feedback_type', models.CharField(choices=[(b'S', b'Survey'), (b'G', b'General'), (b'P', b'Personality'), (b'R', b'Review'), (b'E', b'Edubot Poll')], max_length=1)),
                ('description', models.TextField()),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Team')),
            ],
            bases=('actions.action',),
        ),
        migrations.CreateModel(
            name='PeerFeedbackAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actions.Action')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_feedbacks_received', to='accounts.Employee')),
            ],
            bases=('actions.action',),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.SurveyResponseChoice'),
        ),
        migrations.AddField(
            model_name='action',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_actions', to='accounts.Employee'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='feedback_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='actions.FeedbackAction'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='peer_feedback_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='actions.PeerFeedbackAction'),
        ),
        migrations.AddField(
            model_name='feedbackinvite',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='actions.FeedbackAction'),
        ),
    ]
