# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 05:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('client_id', models.CharField(max_length=300)),
                ('client_secret', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('slack_username', models.CharField(blank=True, max_length=100, null=True)),
                ('slack_tz_label', models.CharField(blank=True, max_length=100, null=True)),
                ('slack_tz', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('optout', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Company')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportees', to='accounts.Employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slack_team_id', models.CharField(blank=True, max_length=20, null=True)),
                ('slack_bot_user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('slack_bot_access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('plan', models.CharField(choices=[(b'F', b'Free'), (b'P', b'Pro'), (b'E', b'Enterprise'), (b'C', b'Closed')], default=b'F', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TeamBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slack_team_id', models.CharField(blank=True, max_length=20, null=True)),
                ('slack_bot_user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('slack_bot_access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('plan', models.CharField(choices=[(b'F', b'Free'), (b'P', b'Pro'), (b'E', b'Enterprise'), (b'C', b'Closed')], default=b'F', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('digest', models.CharField(blank=True, max_length=20, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='accounts.Bot')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='accounts.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='accounts.Employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.Team')),
            ],
        ),
    ]
