# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=50)),
                ('dm', models.BooleanField(default=True)),
                ('msg_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='accounts.Employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_messages', to='accounts.Team')),
                ('team_bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ic_messages', to='accounts.TeamBot')),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[(b'FB', b'Feedback'), (b'GM', b'Game'), (b'PS', b'From prompt set'), (b'FC', b'Fact'), (b'TX', b'Text response')], max_length=50)),
                ('channel', models.CharField(max_length=50)),
                ('dm', models.BooleanField(default=True)),
                ('msg_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_prompts', to='accounts.Employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_prompts', to='accounts.Team')),
                ('team_bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teambot_prompts', to='accounts.TeamBot')),
            ],
        ),
        migrations.CreateModel(
            name='TeamBotOnboarding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(b'RG', b'Registered'), (b'OD', b'DM sent to owner'), (b'GJ', b'public channel joined'), (b'ID', b'Introduced on a public channel')], default=b'RG', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_state', to='accounts.TeamBot')),
            ],
        ),
        migrations.CreateModel(
            name='TeamOnboarding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(b'RG', b'Registered'), (b'OD', b'DM sent to owner'), (b'GJ', b'public channel joined'), (b'ID', b'Introduced on a public channel')], default=b'RG', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_state', to='accounts.Team')),
            ],
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(b'CH', b'Chilling'), (b'FR', b'Feedback requested'), (b'FK', b'Fact requested'), (b'RA', b'Response awaited'), (b'QR', b'Quiz requested'), (b'AA', b'Answer awaited'), (b'CA', b'Fact awaited'), (b'PR', b'Profile requested'), (b'RTR', b'Recognition target requested'), (b'CNA', b'Try another confirmation awaited'), (b'CFA', b'Custom fact awaited'), (b'CSA', b'Custom survey question awaited'), (b'PRP', b'Peer review process'), (b'PLA', b'Peers list awaited'), (b'FRR', b'Feedback recepient requested'), (b'CRD', b'Country requested'), (b'MGA', b'Manager awaited'), (b'FAPA', b'Forward article recepient awaited'), (b'PQA', b'Poll question awaited'), (b'EPA', b'Edubot poll question awaited'), (b'RMCA', b'Reminder confirmation awaited'), (b'ESQA', b'Edubot student question awaited')], default=b'CH', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_state', models.CharField(choices=[(b'CH', b'Chilling'), (b'FR', b'Feedback requested'), (b'FK', b'Fact requested'), (b'RA', b'Response awaited'), (b'QR', b'Quiz requested'), (b'AA', b'Answer awaited'), (b'CA', b'Fact awaited'), (b'PR', b'Profile requested'), (b'RTR', b'Recognition target requested'), (b'CNA', b'Try another confirmation awaited'), (b'CFA', b'Custom fact awaited'), (b'CSA', b'Custom survey question awaited'), (b'PRP', b'Peer review process'), (b'PLA', b'Peers list awaited'), (b'FRR', b'Feedback recepient requested'), (b'CRD', b'Country requested'), (b'MGA', b'Manager awaited'), (b'FAPA', b'Forward article recepient awaited'), (b'PQA', b'Poll question awaited'), (b'EPA', b'Edubot poll question awaited'), (b'RMCA', b'Reminder confirmation awaited'), (b'ESQA', b'Edubot student question awaited')], default=b'CH', max_length=50)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Bot')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_state', to='accounts.Employee')),
            ],
        ),
    ]
